version: '3.8'

services:
  api-test:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 3
  db:
    image: postgres:15.1-alpine
    env_file: .env
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 3