version: '3.8'

services:
  api-test:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000" 
  db:
    image: postgres:15.1-alpine
    env_file: .env
